### ISSUE TITLE
examples with find_package(PythonLibs REQUIRED) don't compile because of conflicting python versions

### ISSUE THREAD

**Issue by astridpetitjean** [arturmiller/pybind11_examples#1]
Hello. 

I noticed that on my machine, Ubuntu18.04 ROS Melodic, the example packages (plugin & cpp_object_attr) do not compile. I do have different python versions installed (version 2.7 and 3.6). 

For python 2.7, I modified the line find_package adding the version 2.7 instead of the default pick 3.6 on my machine:
```
find_package(PythonLibs 2.7 REQUIRED)
``` 

For python 3.6, I modified my catkin config adding some CMake flags forcing catkin to use python 3.6 for compilation. For me it looks like this:  
```
catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
```
I am fairly new to all this and was wondering if what I did is the "proper way" to handle this or if there is a better way? 
I would really appreciate if there could be an example illustrating how to use pybind11_catkin to generate e.g. several versions of the target, one for python 2.7 and one for 3.6 (and others)? I struggle a little with the flags and python version conflicts.

**Comment by arturmiller** [comment]
Hello,

currently, I have no experience using pybind11 with ROS and Python3. My experience is that ROS didn't work well with Python3 until ROS noetic. Nevertheless, I think I will find in the next days a few hours to work on an updated version of these examples, with Python3.
